version: '3.3'

# https://containo.us/blog/traefik-2-0-docker-101-fc2893944b9d/

services:
  traefik:
    image: "traefik:v2.1.2"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      #- "--api.insecure=true"
      - "--api"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - --certificatesresolvers.le.acme.email=stb@lassitu.de
      - --certificatesresolvers.le.acme.storage=/acme/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "acme:/acme"
      - "./admin-users.htpasswd:/htpasswd"
    labels:
      - "traefik.enable=true"
#      - "traefik.http.routers.traefik.rule=Host(`traefik.wiki.c3lingo.org`)"
#      - "traefik.http.routers.traefik.service=api@internal"
#      - "traefik.http.routers.traefik.middlewares=admin"
#      - "traefik.http.routers.traefik.tls.certresolver=le"
#      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.middlewares.admin.basicauth.usersfile=/htpasswd"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
  
  certsdumper:
    image: ldez/traefik-certs-dumper
    restart: always
    command:
      - "file"
      - "--version"
      - "v2"
      - "--source"
      - "/acme/acme.json"
      - "--dest"
      - "/certs"
    volumes:
      - "acme:/acme"
      - "./certs:/certs"

  dokuwiki:
    build: dokuwiki
    restart: always
    volumes:
      - ./html:/var/www/html
      - ./msmtprc:/etc/msmtprc
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wiki.c3lingo.org`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=le"

  murmur:
    image: goofball222/murmur
    restart: always
    ports:
      - 64738:64738
      - 64738:64738/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./murmur/cert:/opt/murmur/cert
      - ./murmur/config:/opt/murmur/config
      - ./murmur/data:/opt/murmur/data
      - ./murmur/log:/opt/murmur/log
    environment:
      - TZ=UTC
      

volumes:
    acme: {}
