version: '3.9'

# https://containo.us/blog/traefik-2-0-docker-101-fc2893944b9d/

services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api"
      - "--api.dashboard=true"
      #- "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/traefik/traefik.yaml"
      #- "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      #- "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - --certificatesresolvers.le.acme.email=stb@lassitu.de
      - --certificatesresolvers.le.acme.storage=/acme/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      #- --certificatesresolvers.le.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
      #- "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "acme:/acme"
      - "./traefik:/traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.c3lingowiki.zs64.net`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=admin"
      - "traefik.http.routers.api.tls.certresolver=le"
      - "traefik.http.routers.api.entrypoints=web,websecure"
      - "traefik.http.middlewares.admin.basicauth.usersfile=/traefik/admin-users.htpasswd"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
  
  certsdumper:
    image: ldez/traefik-certs-dumper
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1d
        max_attempts: 1000
    command:
      - "file"
      - "--version"
      - "v2"
      - "--source"
      - "/acme/acme.json"
      - "--dest"
      - "/certs"
    volumes:
      - "acme:/acme"
      - "./certs:/certs"

  dokuwiki:
    build: dokuwiki
    restart: always
    volumes:
      - ./html:/var/www/html
      - ./msmtprc:/etc/msmtprc
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dokuwiki.rule=Host(`wiki.c3lingo.org`)"
      - "traefik.http.routers.dokuwiki.entrypoints=websecure"
      - "traefik.http.routers.dokuwiki.tls.certresolver=le"

  murmur:
    image: goofball222/murmur
    restart: always
    ports:
      - 64738:64738
      - 64738:64738/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./murmur/cert:/opt/murmur/cert
      - ./murmur/config:/opt/murmur/config
      - ./murmur/data:/opt/murmur/data
      - ./murmur/log:/opt/murmur/log
      - "./certs:/certs"
    environment:
      - TZ=UTC

  c3lingotest:
    image: c3lingo/c3lingo-mumble:latest
    command: "-m c3lingo_mumble.play_wav -c /c3lingo-mumbleweb/test-channel.yaml"
    volumes:
      - "./c3lingo-mumbleweb:/c3lingo-mumbleweb"
      
  mumbleweb:
    image: c3lingo/mumble-web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mumble.rule=Host(`mumble.c3lingo.org`)"
      - "traefik.http.routers.mumble.entrypoints=websecure"
      - "traefik.http.routers.mumble.tls.certresolver=le"


volumes:
    acme: {}
