---
http:
  routers:
    mumble-schedule:
      entryPoints:
      - websecure
      rule: "Host(`mumble.c3lingo.org`) && Path(`/fahrplan.xml`)"
      priority: 1000
      middlewares:
      - mumble-schedule
      - updateHeadersChaotikum
      service: schedule
      tls:
        certresolver: le
  middlewares:
    mumble-schedule:
      replacePath:
        path: "/ptt/schedule/export/schedule.xml"
    updateHeadersChaotikum:
      headers:
        customRequestHeaders:
          Host: talks.mrmcd.net
  services:
    schedule:
      loadBalancer:
        servers:
        - url: "https://talks.mrmcd.net/"
