---
http:
  routers:
    mumble-schedule:
      entryPoints:
      - websecure
      rule: "Host(`mumble.c3lingo.org`) && Path(`/schedule.json`)"
      priority: 1000
      middlewares:
      - mumble-schedule
      - updateHeadersChaotikum
      service: schedule
      tls:
        certresolver: le
  middlewares:
    mumble-schedule:
      replacePath:
        path: "/divoc-reboot-to-respawn-2021/schedule/export/schedule.json"
    updateHeadersChaotikum:
      headers:
        customRequestHeaders:
          Host: data.c3voc.de
  services:
    schedule:
      loadBalancer:
        servers:
        - url: "https://pretalx.c3voc.de/"
